import 'package:direct_app/model/ddi_model.dart';
import 'package:intl/intl.dart';

class TextoClass {
  String limparDdi(String value) {
    String output = value.replaceAll(' ', '').replaceAll('+', '');
    return output;
  }

  String formatarTelefone(int numero) {
    String numeroString = numero.toString();

    if (numeroString.length == 10) {
      return '(${numeroString.substring(0, 2)}) ${numeroString.substring(2, 6)}-${numeroString.substring(6)}';
    } else if (numeroString.length == 11) {
      return '(${numeroString.substring(0, 2)}) ${numeroString.substring(2, 7)}-${numeroString.substring(7)}';
    } else {
      return numeroString;
    }
  }

  String formatarTelefoneCompleto(String value) {
    value = value.trim();
    value = '+$value';
    value = value.replaceAll('(', ' (');
    value = value.replaceAll(')', ') ');
    return value;
  }

  String formatarData(String value) {
    DateTime dateTime = DateTime.parse(value);

    String formattedDate =
        DateFormat("dd MMM. 'de' yyyy 'às' HH'h'mm'm'").format(dateTime);

    return formattedDate;
  }
}

final List<DdiModel> listaDdi = [
  DdiModel(
    nome: "Afghanistan",
    bandeira: "🇦🇫",
    codigo: "AF",
    ddi: "+93",
  ),
  DdiModel(
    nome: "Åland Islands",
    bandeira: "🇦🇽",
    codigo: "AX",
    ddi: "+358",
  ),
  DdiModel(
    nome: "Albania",
    bandeira: "🇦🇱",
    codigo: "AL",
    ddi: "+355",
  ),
  DdiModel(
    nome: "Algeria",
    bandeira: "🇩🇿",
    codigo: "DZ",
    ddi: "+213",
  ),
  DdiModel(
    nome: "American Samoa",
    bandeira: "🇦🇸",
    codigo: "AS",
    ddi: "+1684",
  ),
  DdiModel(
    nome: "Andorra",
    bandeira: "🇦🇩",
    codigo: "AD",
    ddi: "+376",
  ),
  DdiModel(
    nome: "Angola",
    bandeira: "🇦🇴",
    codigo: "AO",
    ddi: "+244",
  ),
  DdiModel(
    nome: "Anguilla",
    bandeira: "🇦🇮",
    codigo: "AI",
    ddi: "+1264",
  ),
  DdiModel(
    nome: "Antarctica",
    bandeira: "🇦🇶",
    codigo: "AQ",
    ddi: "+672",
  ),
  DdiModel(
    nome: "Antigua and Barbuda",
    bandeira: "🇦🇬",
    codigo: "AG",
    ddi: "+1268",
  ),
  DdiModel(
    nome: "Argentina",
    bandeira: "🇦🇷",
    codigo: "AR",
    ddi: "+54",
  ),
  DdiModel(
    nome: "Armenia",
    bandeira: "🇦🇲",
    codigo: "AM",
    ddi: "+374",
  ),
  DdiModel(
    nome: "Aruba",
    bandeira: "🇦🇼",
    codigo: "AW",
    ddi: "+297",
  ),
  DdiModel(
    nome: "Australia",
    bandeira: "🇦🇺",
    codigo: "AU",
    ddi: "+61",
  ),
  DdiModel(
    nome: "Austria",
    bandeira: "🇦🇹",
    codigo: "AT",
    ddi: "+43",
  ),
  DdiModel(
    nome: "Azerbaijan",
    bandeira: "🇦🇿",
    codigo: "AZ",
    ddi: "+994",
  ),
  DdiModel(
    nome: "Bahamas",
    bandeira: "🇧🇸",
    codigo: "BS",
    ddi: "+1242",
  ),
  DdiModel(
    nome: "Bahrain",
    bandeira: "🇧🇭",
    codigo: "BH",
    ddi: "+973",
  ),
  DdiModel(
    nome: "Bangladesh",
    bandeira: "🇧🇩",
    codigo: "BD",
    ddi: "+880",
  ),
  DdiModel(
    nome: "Barbados",
    bandeira: "🇧🇧",
    codigo: "BB",
    ddi: "+1246",
  ),
  DdiModel(
    nome: "Belarus",
    bandeira: "🇧🇾",
    codigo: "BY",
    ddi: "+375",
  ),
  DdiModel(
    nome: "Belgium",
    bandeira: "🇧🇪",
    codigo: "BE",
    ddi: "+32",
  ),
  DdiModel(
    nome: "Belize",
    bandeira: "🇧🇿",
    codigo: "BZ",
    ddi: "+501",
  ),
  DdiModel(
    nome: "Benin",
    bandeira: "🇧🇯",
    codigo: "BJ",
    ddi: "+229",
  ),
  DdiModel(
    nome: "Bermuda",
    bandeira: "🇧🇲",
    codigo: "BM",
    ddi: "+1441",
  ),
  DdiModel(
    nome: "Bhutan",
    bandeira: "🇧🇹",
    codigo: "BT",
    ddi: "+975",
  ),
  DdiModel(
    nome: "Bolivia, Plurinational State of bolivia",
    bandeira: "🇧🇴",
    codigo: "BO",
    ddi: "+591",
  ),
  DdiModel(
    nome: "Bosnia and Herzegovina",
    bandeira: "🇧🇦",
    codigo: "BA",
    ddi: "+387",
  ),
  DdiModel(
    nome: "Botswana",
    bandeira: "🇧🇼",
    codigo: "BW",
    ddi: "+267",
  ),
  DdiModel(
    nome: "Bouvet Island",
    bandeira: "🇧🇻",
    codigo: "BV",
    ddi: "+47",
  ),
  DdiModel(
    nome: "Brazil",
    bandeira: "🇧🇷",
    codigo: "BR",
    ddi: "+55",
  ),
  DdiModel(
    nome: "British Indian Ocean Territory",
    bandeira: "🇮🇴",
    codigo: "IO",
    ddi: "+246",
  ),
  DdiModel(
    nome: "Brunei Darussalam",
    bandeira: "🇧🇳",
    codigo: "BN",
    ddi: "+673",
  ),
  DdiModel(
    nome: "Bulgaria",
    bandeira: "🇧🇬",
    codigo: "BG",
    ddi: "+359",
  ),
  DdiModel(
    nome: "Burkina Faso",
    bandeira: "🇧🇫",
    codigo: "BF",
    ddi: "+226",
  ),
  DdiModel(
    nome: "Burundi",
    bandeira: "🇧🇮",
    codigo: "BI",
    ddi: "+257",
  ),
  DdiModel(
    nome: "Cambodia",
    bandeira: "🇰🇭",
    codigo: "KH",
    ddi: "+855",
  ),
  DdiModel(
    nome: "Cameroon",
    bandeira: "🇨🇲",
    codigo: "CM",
    ddi: "+237",
  ),
  DdiModel(
    nome: "Canada",
    bandeira: "🇨🇦",
    codigo: "CA",
    ddi: "+1",
  ),
  DdiModel(
    nome: "Cape Verde",
    bandeira: "🇨🇻",
    codigo: "CV",
    ddi: "+238",
  ),
  DdiModel(
    nome: "Cayman Islands",
    bandeira: "🇰🇾",
    codigo: "KY",
    ddi: "+345",
  ),
  DdiModel(
    nome: "Central African Republic",
    bandeira: "🇨🇫",
    codigo: "CF",
    ddi: "+236",
  ),
  DdiModel(
    nome: "Chad",
    bandeira: "🇹🇩",
    codigo: "TD",
    ddi: "+235",
  ),
  DdiModel(
    nome: "Chile",
    bandeira: "🇨🇱",
    codigo: "CL",
    ddi: "+56",
  ),
  DdiModel(
    nome: "China",
    bandeira: "🇨🇳",
    codigo: "CN",
    ddi: "+86",
  ),
  DdiModel(
    nome: "Christmas Island",
    bandeira: "🇨🇽",
    codigo: "CX",
    ddi: "+61",
  ),
  DdiModel(
    nome: "Cocos (Keeling) Islands",
    bandeira: "🇨🇨",
    codigo: "CC",
    ddi: "+61",
  ),
  DdiModel(
    nome: "Colombia",
    bandeira: "🇨🇴",
    codigo: "CO",
    ddi: "+57",
  ),
  DdiModel(
    nome: "Comoros",
    bandeira: "🇰🇲",
    codigo: "KM",
    ddi: "+269",
  ),
  DdiModel(
    nome: "Congo",
    bandeira: "🇨🇬",
    codigo: "CG",
    ddi: "+242",
  ),
  DdiModel(
    nome: "Congo, The Democratic Republic of the Congo",
    bandeira: "🇨🇩",
    codigo: "CD",
    ddi: "+243",
  ),
  DdiModel(
    nome: "Cook Islands",
    bandeira: "🇨🇰",
    codigo: "CK",
    ddi: "+682",
  ),
  DdiModel(
    nome: "Costa Rica",
    bandeira: "🇨🇷",
    codigo: "CR",
    ddi: "+506",
  ),
  DdiModel(
    nome: "Cote d'Ivoire",
    bandeira: "🇨🇮",
    codigo: "CI",
    ddi: "+225",
  ),
  DdiModel(
    nome: "Croatia",
    bandeira: "🇭🇷",
    codigo: "HR",
    ddi: "+385",
  ),
  DdiModel(
    nome: "Cuba",
    bandeira: "🇨🇺",
    codigo: "CU",
    ddi: "+53",
  ),
  DdiModel(
    nome: "Cyprus",
    bandeira: "🇨🇾",
    codigo: "CY",
    ddi: "+357",
  ),
  DdiModel(
    nome: "Czech Republic",
    bandeira: "🇨🇿",
    codigo: "CZ",
    ddi: "+420",
  ),
  DdiModel(
    nome: "Denmark",
    bandeira: "🇩🇰",
    codigo: "DK",
    ddi: "+45",
  ),
  DdiModel(
    nome: "Djibouti",
    bandeira: "🇩🇯",
    codigo: "DJ",
    ddi: "+253",
  ),
  DdiModel(
    nome: "Dominica",
    bandeira: "🇩🇲",
    codigo: "DM",
    ddi: "+1767",
  ),
  DdiModel(
    nome: "Dominican Republic",
    bandeira: "🇩🇴",
    codigo: "DO",
    ddi: "+1849",
  ),
  DdiModel(
    nome: "Ecuador",
    bandeira: "🇪🇨",
    codigo: "EC",
    ddi: "+593",
  ),
  DdiModel(
    nome: "Egypt",
    bandeira: "🇪🇬",
    codigo: "EG",
    ddi: "+20",
  ),
  DdiModel(
    nome: "El Salvador",
    bandeira: "🇸🇻",
    codigo: "SV",
    ddi: "+503",
  ),
  DdiModel(
    nome: "Equatorial Guinea",
    bandeira: "🇬🇶",
    codigo: "GQ",
    ddi: "+240",
  ),
  DdiModel(
    nome: "Eritrea",
    bandeira: "🇪🇷",
    codigo: "ER",
    ddi: "+291",
  ),
  DdiModel(
    nome: "Estonia",
    bandeira: "🇪🇪",
    codigo: "EE",
    ddi: "+372",
  ),
  DdiModel(
    nome: "Ethiopia",
    bandeira: "🇪🇹",
    codigo: "ET",
    ddi: "+251",
  ),
  DdiModel(
    nome: "Falkland Islands (Malvinas)",
    bandeira: "🇫🇰",
    codigo: "FK",
    ddi: "+500",
  ),
  DdiModel(
    nome: "Faroe Islands",
    bandeira: "🇫🇴",
    codigo: "FO",
    ddi: "+298",
  ),
  DdiModel(
    nome: "Fiji",
    bandeira: "🇫🇯",
    codigo: "FJ",
    ddi: "+679",
  ),
  DdiModel(
    nome: "Finland",
    bandeira: "🇫🇮",
    codigo: "FI",
    ddi: "+358",
  ),
  DdiModel(
    nome: "France",
    bandeira: "🇫🇷",
    codigo: "FR",
    ddi: "+33",
  ),
  DdiModel(
    nome: "French Guiana",
    bandeira: "🇬🇫",
    codigo: "GF",
    ddi: "+594",
  ),
  DdiModel(
    nome: "French Polynesia",
    bandeira: "🇵🇫",
    codigo: "PF",
    ddi: "+689",
  ),
  DdiModel(
    nome: "French Southern Territories",
    bandeira: "🇹🇫",
    codigo: "TF",
    ddi: "+262",
  ),
  DdiModel(
    nome: "Gabon",
    bandeira: "🇬🇦",
    codigo: "GA",
    ddi: "+241",
  ),
  DdiModel(
    nome: "Gambia",
    bandeira: "🇬🇲",
    codigo: "GM",
    ddi: "+220",
  ),
  DdiModel(
    nome: "Georgia",
    bandeira: "🇬🇪",
    codigo: "GE",
    ddi: "+995",
  ),
  DdiModel(
    nome: "Germany",
    bandeira: "🇩🇪",
    codigo: "DE",
    ddi: "+49",
  ),
  DdiModel(
    nome: "Ghana",
    bandeira: "🇬🇭",
    codigo: "GH",
    ddi: "+233",
  ),
  DdiModel(
    nome: "Gibraltar",
    bandeira: "🇬🇮",
    codigo: "GI",
    ddi: "+350",
  ),
  DdiModel(
    nome: "Greece",
    bandeira: "🇬🇷",
    codigo: "GR",
    ddi: "+30",
  ),
  DdiModel(
    nome: "Greenland",
    bandeira: "🇬🇱",
    codigo: "GL",
    ddi: "+299",
  ),
  DdiModel(
    nome: "Grenada",
    bandeira: "🇬🇩",
    codigo: "GD",
    ddi: "+1473",
  ),
  DdiModel(
    nome: "Guadeloupe",
    bandeira: "🇬🇵",
    codigo: "GP",
    ddi: "+590",
  ),
  DdiModel(
    nome: "Guam",
    bandeira: "🇬🇺",
    codigo: "GU",
    ddi: "+1671",
  ),
  DdiModel(
    nome: "Guatemala",
    bandeira: "🇬🇹",
    codigo: "GT",
    ddi: "+502",
  ),
  DdiModel(
    nome: "Guernsey",
    bandeira: "🇬🇬",
    codigo: "GG",
    ddi: "+44",
  ),
  DdiModel(
    nome: "Guinea",
    bandeira: "🇬🇳",
    codigo: "GN",
    ddi: "+224",
  ),
  DdiModel(
    nome: "Guinea-Bissau",
    bandeira: "🇬🇼",
    codigo: "GW",
    ddi: "+245",
  ),
  DdiModel(
    nome: "Guyana",
    bandeira: "🇬🇾",
    codigo: "GY",
    ddi: "+592",
  ),
  DdiModel(
    nome: "Haiti",
    bandeira: "🇭🇹",
    codigo: "HT",
    ddi: "+509",
  ),
  DdiModel(
    nome: "Heard Island and Mcdonald Islands",
    bandeira: "🇭🇲",
    codigo: "HM",
    ddi: "+672",
  ),
  DdiModel(
    nome: "Holy See (Vatican City State)",
    bandeira: "🇻🇦",
    codigo: "VA",
    ddi: "+379",
  ),
  DdiModel(
    nome: "Honduras",
    bandeira: "🇭🇳",
    codigo: "HN",
    ddi: "+504",
  ),
  DdiModel(
    nome: "Hong Kong",
    bandeira: "🇭🇰",
    codigo: "HK",
    ddi: "+852",
  ),
  DdiModel(
    nome: "Hungary",
    bandeira: "🇭🇺",
    codigo: "HU",
    ddi: "+36",
  ),
  DdiModel(
    nome: "Iceland",
    bandeira: "🇮🇸",
    codigo: "IS",
    ddi: "+354",
  ),
  DdiModel(
    nome: "India",
    bandeira: "🇮🇳",
    codigo: "IN",
    ddi: "+91",
  ),
  DdiModel(
    nome: "Indonesia",
    bandeira: "🇮🇩",
    codigo: "ID",
    ddi: "+62",
  ),
  DdiModel(
    nome: "Iran, Islamic Republic of Persian Gulf",
    bandeira: "🇮🇷",
    codigo: "IR",
    ddi: "+98",
  ),
  DdiModel(
    nome: "Iraq",
    bandeira: "🇮🇶",
    codigo: "IQ",
    ddi: "+964",
  ),
  DdiModel(
    nome: "Ireland",
    bandeira: "🇮🇪",
    codigo: "IE",
    ddi: "+353",
  ),
  DdiModel(
    nome: "Isle of Man",
    bandeira: "🇮🇲",
    codigo: "IM",
    ddi: "+44",
  ),
  DdiModel(
    nome: "Israel",
    bandeira: "🇮🇱",
    codigo: "IL",
    ddi: "+972",
  ),
  DdiModel(
    nome: "Italy",
    bandeira: "🇮🇹",
    codigo: "IT",
    ddi: "+39",
  ),
  DdiModel(
    nome: "Jamaica",
    bandeira: "🇯🇲",
    codigo: "JM",
    ddi: "+1876",
  ),
  DdiModel(
    nome: "Japan",
    bandeira: "🇯🇵",
    codigo: "JP",
    ddi: "+81",
  ),
  DdiModel(
    nome: "Jersey",
    bandeira: "🇯🇪",
    codigo: "JE",
    ddi: "+44",
  ),
  DdiModel(
    nome: "Jordan",
    bandeira: "🇯🇴",
    codigo: "JO",
    ddi: "+962",
  ),
  DdiModel(
    nome: "Kazakhstan",
    bandeira: "🇰🇿",
    codigo: "KZ",
    ddi: "+7",
  ),
  DdiModel(
    nome: "Kenya",
    bandeira: "🇰🇪",
    codigo: "KE",
    ddi: "+254",
  ),
  DdiModel(
    nome: "Kiribati",
    bandeira: "🇰🇮",
    codigo: "KI",
    ddi: "+686",
  ),
  DdiModel(
    nome: "Korea, Democratic People's Republic of Korea",
    bandeira: "🇰🇵",
    codigo: "KP",
    ddi: "+850",
  ),
  DdiModel(
    nome: "Korea, Republic of South Korea",
    bandeira: "🇰🇷",
    codigo: "KR",
    ddi: "+82",
  ),
  DdiModel(
    nome: "Kosovo",
    bandeira: "🇽🇰",
    codigo: "XK",
    ddi: "+383",
  ),
  DdiModel(
    nome: "Kuwait",
    bandeira: "🇰🇼",
    codigo: "KW",
    ddi: "+965",
  ),
  DdiModel(
    nome: "Kyrgyzstan",
    bandeira: "🇰🇬",
    codigo: "KG",
    ddi: "+996",
  ),
  DdiModel(
    nome: "Laos",
    bandeira: "🇱🇦",
    codigo: "LA",
    ddi: "+856",
  ),
  DdiModel(
    nome: "Latvia",
    bandeira: "🇱🇻",
    codigo: "LV",
    ddi: "+371",
  ),
  DdiModel(
    nome: "Lebanon",
    bandeira: "🇱🇧",
    codigo: "LB",
    ddi: "+961",
  ),
  DdiModel(
    nome: "Lesotho",
    bandeira: "🇱🇸",
    codigo: "LS",
    ddi: "+266",
  ),
  DdiModel(
    nome: "Liberia",
    bandeira: "🇱🇷",
    codigo: "LR",
    ddi: "+231",
  ),
  DdiModel(
    nome: "Libyan Arab Jamahiriya",
    bandeira: "🇱🇾",
    codigo: "LY",
    ddi: "+218",
  ),
  DdiModel(
    nome: "Liechtenstein",
    bandeira: "🇱🇮",
    codigo: "LI",
    ddi: "+423",
  ),
  DdiModel(
    nome: "Lithuania",
    bandeira: "🇱🇹",
    codigo: "LT",
    ddi: "+370",
  ),
  DdiModel(
    nome: "Luxembourg",
    bandeira: "🇱🇺",
    codigo: "LU",
    ddi: "+352",
  ),
  DdiModel(
    nome: "Macao",
    bandeira: "🇲🇴",
    codigo: "MO",
    ddi: "+853",
  ),
  DdiModel(
    nome: "Macedonia",
    bandeira: "🇲🇰",
    codigo: "MK",
    ddi: "+389",
  ),
  DdiModel(
    nome: "Madagascar",
    bandeira: "🇲🇬",
    codigo: "MG",
    ddi: "+261",
  ),
  DdiModel(
    nome: "Malawi",
    bandeira: "🇲🇼",
    codigo: "MW",
    ddi: "+265",
  ),
  DdiModel(
    nome: "Malaysia",
    bandeira: "🇲🇾",
    codigo: "MY",
    ddi: "+60",
  ),
  DdiModel(
    nome: "Maldives",
    bandeira: "🇲🇻",
    codigo: "MV",
    ddi: "+960",
  ),
  DdiModel(
    nome: "Mali",
    bandeira: "🇲🇱",
    codigo: "ML",
    ddi: "+223",
  ),
  DdiModel(
    nome: "Malta",
    bandeira: "🇲🇹",
    codigo: "MT",
    ddi: "+356",
  ),
  DdiModel(
    nome: "Marshall Islands",
    bandeira: "🇲🇭",
    codigo: "MH",
    ddi: "+692",
  ),
  DdiModel(
    nome: "Martinique",
    bandeira: "🇲🇶",
    codigo: "MQ",
    ddi: "+596",
  ),
  DdiModel(
    nome: "Mauritania",
    bandeira: "🇲🇷",
    codigo: "MR",
    ddi: "+222",
  ),
  DdiModel(
    nome: "Mauritius",
    bandeira: "🇲🇺",
    codigo: "MU",
    ddi: "+230",
  ),
  DdiModel(
    nome: "Mayotte",
    bandeira: "🇾🇹",
    codigo: "YT",
    ddi: "+262",
  ),
  DdiModel(
    nome: "Mexico",
    bandeira: "🇲🇽",
    codigo: "MX",
    ddi: "+52",
  ),
  DdiModel(
    nome: "Micronesia, Federated States of Micronesia",
    bandeira: "🇫🇲",
    codigo: "FM",
    ddi: "+691",
  ),
  DdiModel(
    nome: "Moldova",
    bandeira: "🇲🇩",
    codigo: "MD",
    ddi: "+373",
  ),
  DdiModel(
    nome: "Monaco",
    bandeira: "🇲🇨",
    codigo: "MC",
    ddi: "+377",
  ),
  DdiModel(
    nome: "Mongolia",
    bandeira: "🇲🇳",
    codigo: "MN",
    ddi: "+976",
  ),
  DdiModel(
    nome: "Montenegro",
    bandeira: "🇲🇪",
    codigo: "ME",
    ddi: "+382",
  ),
  DdiModel(
    nome: "Montserrat",
    bandeira: "🇲🇸",
    codigo: "MS",
    ddi: "+1664",
  ),
  DdiModel(
    nome: "Morocco",
    bandeira: "🇲🇦",
    codigo: "MA",
    ddi: "+212",
  ),
  DdiModel(
    nome: "Mozambique",
    bandeira: "🇲🇿",
    codigo: "MZ",
    ddi: "+258",
  ),
  DdiModel(
    nome: "Myanmar",
    bandeira: "🇲🇲",
    codigo: "MM",
    ddi: "+95",
  ),
  DdiModel(
    nome: "Namibia",
    bandeira: "🇳🇦",
    codigo: "NA",
    ddi: "+264",
  ),
  DdiModel(
    nome: "Nauru",
    bandeira: "🇳🇷",
    codigo: "NR",
    ddi: "+674",
  ),
  DdiModel(
    nome: "Nepal",
    bandeira: "🇳🇵",
    codigo: "NP",
    ddi: "+977",
  ),
  DdiModel(
    nome: "Netherlands",
    bandeira: "🇳🇱",
    codigo: "NL",
    ddi: "+31",
  ),
  DdiModel(
    nome: "Netherlands Antilles",
    bandeira: "",
    codigo: "AN",
    ddi: "+599",
  ),
  DdiModel(
    nome: "New Caledonia",
    bandeira: "🇳🇨",
    codigo: "NC",
    ddi: "+687",
  ),
  DdiModel(
    nome: "New Zealand",
    bandeira: "🇳🇿",
    codigo: "NZ",
    ddi: "+64",
  ),
  DdiModel(
    nome: "Nicaragua",
    bandeira: "🇳🇮",
    codigo: "NI",
    ddi: "+505",
  ),
  DdiModel(
    nome: "Niger",
    bandeira: "🇳🇪",
    codigo: "NE",
    ddi: "+227",
  ),
  DdiModel(
    nome: "Nigeria",
    bandeira: "🇳🇬",
    codigo: "NG",
    ddi: "+234",
  ),
  DdiModel(
    nome: "Niue",
    bandeira: "🇳🇺",
    codigo: "NU",
    ddi: "+683",
  ),
  DdiModel(
    nome: "Norfolk Island",
    bandeira: "🇳🇫",
    codigo: "NF",
    ddi: "+672",
  ),
  DdiModel(
    nome: "Northern Mariana Islands",
    bandeira: "🇲🇵",
    codigo: "MP",
    ddi: "+1670",
  ),
  DdiModel(
    nome: "Norway",
    bandeira: "🇳🇴",
    codigo: "NO",
    ddi: "+47",
  ),
  DdiModel(
    nome: "Oman",
    bandeira: "🇴🇲",
    codigo: "OM",
    ddi: "+968",
  ),
  DdiModel(
    nome: "Pakistan",
    bandeira: "🇵🇰",
    codigo: "PK",
    ddi: "+92",
  ),
  DdiModel(
    nome: "Palau",
    bandeira: "🇵🇼",
    codigo: "PW",
    ddi: "+680",
  ),
  DdiModel(
    nome: "Palestinian Territory, Occupied",
    bandeira: "🇵🇸",
    codigo: "PS",
    ddi: "+970",
  ),
  DdiModel(
    nome: "Panama",
    bandeira: "🇵🇦",
    codigo: "PA",
    ddi: "+507",
  ),
  DdiModel(
    nome: "Papua New Guinea",
    bandeira: "🇵🇬",
    codigo: "PG",
    ddi: "+675",
  ),
  DdiModel(
    nome: "Paraguay",
    bandeira: "🇵🇾",
    codigo: "PY",
    ddi: "+595",
  ),
  DdiModel(
    nome: "Peru",
    bandeira: "🇵🇪",
    codigo: "PE",
    ddi: "+51",
  ),
  DdiModel(
    nome: "Philippines",
    bandeira: "🇵🇭",
    codigo: "PH",
    ddi: "+63",
  ),
  DdiModel(
    nome: "Pitcairn",
    bandeira: "🇵🇳",
    codigo: "PN",
    ddi: "+64",
  ),
  DdiModel(
    nome: "Poland",
    bandeira: "🇵🇱",
    codigo: "PL",
    ddi: "+48",
  ),
  DdiModel(
    nome: "Portugal",
    bandeira: "🇵🇹",
    codigo: "PT",
    ddi: "+351",
  ),
  DdiModel(
    nome: "Puerto Rico",
    bandeira: "🇵🇷",
    codigo: "PR",
    ddi: "+1939",
  ),
  DdiModel(
    nome: "Qatar",
    bandeira: "🇶🇦",
    codigo: "QA",
    ddi: "+974",
  ),
  DdiModel(
    nome: "Romania",
    bandeira: "🇷🇴",
    codigo: "RO",
    ddi: "+40",
  ),
  DdiModel(
    nome: "Russia",
    bandeira: "🇷🇺",
    codigo: "RU",
    ddi: "+7",
  ),
  DdiModel(
    nome: "Rwanda",
    bandeira: "🇷🇼",
    codigo: "RW",
    ddi: "+250",
  ),
  DdiModel(
    nome: "Reunion",
    bandeira: "🇷🇪",
    codigo: "RE",
    ddi: "+262",
  ),
  DdiModel(
    nome: "Saint Barthelemy",
    bandeira: "🇧🇱",
    codigo: "BL",
    ddi: "+590",
  ),
  DdiModel(
    nome: "Saint Helena, Ascension and Tristan Da Cunha",
    bandeira: "🇸🇭",
    codigo: "SH",
    ddi: "+290",
  ),
  DdiModel(
    nome: "Saint Kitts and Nevis",
    bandeira: "🇰🇳",
    codigo: "KN",
    ddi: "+1869",
  ),
  DdiModel(
    nome: "Saint Lucia",
    bandeira: "🇱🇨",
    codigo: "LC",
    ddi: "+1758",
  ),
  DdiModel(
    nome: "Saint Martin",
    bandeira: "🇲🇫",
    codigo: "MF",
    ddi: "+590",
  ),
  DdiModel(
    nome: "Saint Pierre and Miquelon",
    bandeira: "🇵🇲",
    codigo: "PM",
    ddi: "+508",
  ),
  DdiModel(
    nome: "Saint Vincent and the Grenadines",
    bandeira: "🇻🇨",
    codigo: "VC",
    ddi: "+1784",
  ),
  DdiModel(
    nome: "Samoa",
    bandeira: "🇼🇸",
    codigo: "WS",
    ddi: "+685",
  ),
  DdiModel(
    nome: "San Marino",
    bandeira: "🇸🇲",
    codigo: "SM",
    ddi: "+378",
  ),
  DdiModel(
    nome: "Sao Tome and Principe",
    bandeira: "🇸🇹",
    codigo: "ST",
    ddi: "+239",
  ),
  DdiModel(
    nome: "Saudi Arabia",
    bandeira: "🇸🇦",
    codigo: "SA",
    ddi: "+966",
  ),
  DdiModel(
    nome: "Senegal",
    bandeira: "🇸🇳",
    codigo: "SN",
    ddi: "+221",
  ),
  DdiModel(
    nome: "Serbia",
    bandeira: "🇷🇸",
    codigo: "RS",
    ddi: "+381",
  ),
  DdiModel(
    nome: "Seychelles",
    bandeira: "🇸🇨",
    codigo: "SC",
    ddi: "+248",
  ),
  DdiModel(
    nome: "Sierra Leone",
    bandeira: "🇸🇱",
    codigo: "SL",
    ddi: "+232",
  ),
  DdiModel(
    nome: "Singapore",
    bandeira: "🇸🇬",
    codigo: "SG",
    ddi: "+65",
  ),
  DdiModel(
    nome: "Slovakia",
    bandeira: "🇸🇰",
    codigo: "SK",
    ddi: "+421",
  ),
  DdiModel(
    nome: "Slovenia",
    bandeira: "🇸🇮",
    codigo: "SI",
    ddi: "+386",
  ),
  DdiModel(
    nome: "Solomon Islands",
    bandeira: "🇸🇧",
    codigo: "SB",
    ddi: "+677",
  ),
  DdiModel(
    nome: "Somalia",
    bandeira: "🇸🇴",
    codigo: "SO",
    ddi: "+252",
  ),
  DdiModel(
    nome: "South Africa",
    bandeira: "🇿🇦",
    codigo: "ZA",
    ddi: "+27",
  ),
  DdiModel(
    nome: "South Sudan",
    bandeira: "🇸🇸",
    codigo: "SS",
    ddi: "+211",
  ),
  DdiModel(
    nome: "South Georgia and the South Sandwich Islands",
    bandeira: "🇬🇸",
    codigo: "GS",
    ddi: "+500",
  ),
  DdiModel(
    nome: "Spain",
    bandeira: "🇪🇸",
    codigo: "ES",
    ddi: "+34",
  ),
  DdiModel(
    nome: "Sri Lanka",
    bandeira: "🇱🇰",
    codigo: "LK",
    ddi: "+94",
  ),
  DdiModel(
    nome: "Sudan",
    bandeira: "🇸🇩",
    codigo: "SD",
    ddi: "+249",
  ),
  DdiModel(
    nome: "Suriname",
    bandeira: "🇸🇷",
    codigo: "SR",
    ddi: "+597",
  ),
  DdiModel(
    nome: "Svalbard and Jan Mayen",
    bandeira: "🇸🇯",
    codigo: "SJ",
    ddi: "+47",
  ),
  DdiModel(
    nome: "Swaziland",
    bandeira: "🇸🇿",
    codigo: "SZ",
    ddi: "+268",
  ),
  DdiModel(
    nome: "Sweden",
    bandeira: "🇸🇪",
    codigo: "SE",
    ddi: "+46",
  ),
  DdiModel(
    nome: "Switzerland",
    bandeira: "🇨🇭",
    codigo: "CH",
    ddi: "+41",
  ),
  DdiModel(
    nome: "Syrian Arab Republic",
    bandeira: "🇸🇾",
    codigo: "SY",
    ddi: "+963",
  ),
  DdiModel(
    nome: "Taiwan",
    bandeira: "🇹🇼",
    codigo: "TW",
    ddi: "+886",
  ),
  DdiModel(
    nome: "Tajikistan",
    bandeira: "🇹🇯",
    codigo: "TJ",
    ddi: "+992",
  ),
  DdiModel(
    nome: "Tanzania, United Republic of Tanzania",
    bandeira: "🇹🇿",
    codigo: "TZ",
    ddi: "+255",
  ),
  DdiModel(
    nome: "Thailand",
    bandeira: "🇹🇭",
    codigo: "TH",
    ddi: "+66",
  ),
  DdiModel(
    nome: "Timor-Leste",
    bandeira: "🇹🇱",
    codigo: "TL",
    ddi: "+670",
  ),
  DdiModel(
    nome: "Togo",
    bandeira: "🇹🇬",
    codigo: "TG",
    ddi: "+228",
  ),
  DdiModel(
    nome: "Tokelau",
    bandeira: "🇹🇰",
    codigo: "TK",
    ddi: "+690",
  ),
  DdiModel(
    nome: "Tonga",
    bandeira: "🇹🇴",
    codigo: "TO",
    ddi: "+676",
  ),
  DdiModel(
    nome: "Trinidad and Tobago",
    bandeira: "🇹🇹",
    codigo: "TT",
    ddi: "+1868",
  ),
  DdiModel(
    nome: "Tunisia",
    bandeira: "🇹🇳",
    codigo: "TN",
    ddi: "+216",
  ),
  DdiModel(
    nome: "Turkey",
    bandeira: "🇹🇷",
    codigo: "TR",
    ddi: "+90",
  ),
  DdiModel(
    nome: "Turkmenistan",
    bandeira: "🇹🇲",
    codigo: "TM",
    ddi: "+993",
  ),
  DdiModel(
    nome: "Turks and Caicos Islands",
    bandeira: "🇹🇨",
    codigo: "TC",
    ddi: "+1649",
  ),
  DdiModel(
    nome: "Tuvalu",
    bandeira: "🇹🇻",
    codigo: "TV",
    ddi: "+688",
  ),
  DdiModel(
    nome: "Uganda",
    bandeira: "🇺🇬",
    codigo: "UG",
    ddi: "+256",
  ),
  DdiModel(
    nome: "Ukraine",
    bandeira: "🇺🇦",
    codigo: "UA",
    ddi: "+380",
  ),
  DdiModel(
    nome: "United Arab Emirates",
    bandeira: "🇦🇪",
    codigo: "AE",
    ddi: "+971",
  ),
  DdiModel(
    nome: "United Kingdom",
    bandeira: "🇬🇧",
    codigo: "GB",
    ddi: "+44",
  ),
  DdiModel(
    nome: "United States",
    bandeira: "🇺🇸",
    codigo: "US",
    ddi: "+1",
  ),
  DdiModel(
    nome: "Uruguay",
    bandeira: "🇺🇾",
    codigo: "UY",
    ddi: "+598",
  ),
  DdiModel(
    nome: "Uzbekistan",
    bandeira: "🇺🇿",
    codigo: "UZ",
    ddi: "+998",
  ),
  DdiModel(
    nome: "Vanuatu",
    bandeira: "🇻🇺",
    codigo: "VU",
    ddi: "+678",
  ),
  DdiModel(
    nome: "Venezuela, Bolivarian Republic of Venezuela",
    bandeira: "🇻🇪",
    codigo: "VE",
    ddi: "+58",
  ),
  DdiModel(
    nome: "Vietnam",
    bandeira: "🇻🇳",
    codigo: "VN",
    ddi: "+84",
  ),
  DdiModel(
    nome: "Virgin Islands, British",
    bandeira: "🇻🇬",
    codigo: "VG",
    ddi: "+1284",
  ),
  DdiModel(
    nome: "Virgin Islands, U.S.",
    bandeira: "🇻🇮",
    codigo: "VI",
    ddi: "+1340",
  ),
  DdiModel(
    nome: "Wallis and Futuna",
    bandeira: "🇼🇫",
    codigo: "WF",
    ddi: "+681",
  ),
  DdiModel(
    nome: "Yemen",
    bandeira: "🇾🇪",
    codigo: "YE",
    ddi: "+967",
  ),
  DdiModel(
    nome: "Zambia",
    bandeira: "🇿🇲",
    codigo: "ZM",
    ddi: "+260",
  ),
  DdiModel(
    nome: "Zimbabwe",
    bandeira: "🇿🇼",
    codigo: "ZW",
    ddi: "+263",
  )
];
